'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { Toaster } from '@/components/ui/toaster';
import { UserProvider } from "@/hooks/useUser";
import SessionProviderWrapper from './sessionProviderWrapper';
import { Nav } from '@/components/Nav';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <SessionProviderWrapper>
        <UserProvider>
          <div className="flex">
            {pathName !== '/login' && <Nav/>}
            <div className="flex-grow p-10">
              {children}
              </div>
          </div>
          <Toaster />
        </UserProvider>
        </SessionProviderWrapper>
        </main>
      </body>
    </html>
  );
}